### ISSUE TITLE
UnsupportedOperationException new in 4.0.3

### ISSUE THREAD

**Issue by shevek** [chocoteam/choco-solver#529]
```
Exception in thread "main" java.lang.UnsupportedOperationException
        at org.chocosolver.util.objects.setDataStructures.linkedlist.Set_LinkedList.remove(Set_LinkedList.java:104)
        at org.chocosolver.util.objects.setDataStructures.StdSet$ListOP.undo(StdSet.java:144)
        at org.chocosolver.memory.trailing.trail.flatten.OperationTrail.worldPop(OperationTrail.java:80)
        at org.chocosolver.memory.trailing.EnvironmentTrailing.worldPop(EnvironmentTrailing.java:84)
        at org.chocosolver.solver.search.loop.move.MoveBinaryDFS.repair(MoveBinaryDFS.java:74)
        at org.chocosolver.solver.Solver.searchLoop(Solver.java:312)
        at org.chocosolver.solver.Solver.solve(Solver.java:251)
```

Fails in 4.0.3. Reversion to 4.0.2 no longer fails.

**Comment by jgFages** [comment]
Hi Shevek,
Thank you for the feedback.
This problem has already been fixed for the next release.

**Comment by cprudhom** [comment]
Related to #517
