### ISSUE TITLE
Explanation-based LNS crashes

### ISSUE THREAD

**Issue by pwn1** [chocoteam/choco-solver#566]
### Expected behavior
Explanation-based LNS to behave similarly to propagation-guided LNS.
### Actual behavior
Explanation-based LNS crashes with the following:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 17, Size: 17
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.chocosolver.solver.search.loop.lns.neighbors.ExplainingCut.fixSomeVariables(ExplainingCut.java:154)
	at org.chocosolver.solver.search.loop.lns.neighbors.SequenceNeighborhood.fixSomeVariables(SequenceNeighborhood.java:71)
	at org.chocosolver.solver.search.loop.move.MoveLNS.extend(MoveLNS.java:116)
	at org.chocosolver.solver.Solver.extend(Solver.java:429)
	at org.chocosolver.solver.Solver.searchLoop(Solver.java:298)
	at org.chocosolver.solver.Solver.solve(Solver.java:264)
	at MEB.main(MEB.java:154)

### Minimal Working Example

Experienced with choco-solver-4.0.5

```java

import org.chocosolver.solver.Model;
import org.chocosolver.solver.variables.IntVar;

//import static org.chocosolver.solver.ResolutionPolicy.MINIMIZE;
import static org.chocosolver.solver.search.strategy.Search.*;

import org.chocosolver.solver.search.loop.lns.neighbors.PropagationGuidedNeighborhood;
import org.chocosolver.solver.search.limits.FailCounter;
import org.chocosolver.solver.search.loop.lns.*;
import org.chocosolver.solver.search.loop.lns.neighbors.*;
import org.chocosolver.solver.search.limits.BacktrackCounter;
import org.chocosolver.solver.search.loop.move.*;
import org.chocosolver.solver.search.strategy.selectors.values.*;
import org.chocosolver.solver.search.strategy.selectors.variables.*;
import org.chocosolver.solver.Solution;
import org.chocosolver.solver.exception.SolverException;
/**
 * Minimum Energy Broadcast
 */
public class MEB {
    
public static void main(String [] args) {
    // Instance copied from meb-inst-18-09.eprime-param
    
    int nodes = 18;
    
    int initialNode= 15;
    
    //  Indexed by parent, child.  Should be symmetric.
    int[][] linkCosts= {
         {0, 0, 0, 104, 0, 52, 0, 0, 0, 0, 0, 0, 0, 2, 0, 20, 0, 73},
         {0, 0, 0, 0, 152, 0, 1, 0, 7, 0, 17, 11, 0, 0, 0, 0, 1, 0},
         {0, 0, 0, 0, 104, 0, 0, 1, 0, 1, 0, 0, 20, 0, 1, 0, 0, 0},
         {104, 0, 0, 0, 0, 5, 151, 0, 100, 0, 191, 0, 0, 0, 0, 8, 0, 0},
         {0, 152, 104, 0, 0, 0, 191, 46, 140, 197, 0, 75, 0, 0, 106, 0, 104, 0},
         {52, 0, 0, 5, 0, 0, 0, 0, 105, 0, 0, 0, 0, 70, 0, 1, 0, 0},
         {0, 1, 0, 151, 191, 0, 0, 0, 1, 0, 11, 46, 0, 0, 0, 0, 14, 0},
         {0, 0, 1, 0, 46, 0, 0, 0, 0, 15, 0, 0, 77, 0, 6, 0, 0, 0},
         {0, 7, 0, 100, 140, 105, 1, 0, 0, 0, 36, 77, 0, 0, 0, 197, 33, 0},
         {0, 0, 1, 0, 197, 0, 0, 15, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0},
         {0, 17, 0, 191, 0, 0, 11, 0, 36, 0, 0, 144, 0, 0, 0, 0, 60, 0},
         {0, 11, 0, 0, 75, 0, 46, 0, 77, 0, 144, 0, 0, 0, 0, 0, 1, 0},
         {0, 0, 20, 0, 0, 0, 0, 77, 0, 2, 0, 0, 0, 0, 6, 0, 0, 0},
         {2, 0, 0, 0, 0, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34, 0, 0},
         {0, 0, 1, 0, 106, 0, 0, 6, 0, 1, 0, 0, 6, 0, 0, 0, 0, 0},
         {20, 0, 0, 8, 0, 1, 0, 0, 197, 0, 0, 0, 0, 34, 0, 0, 0, 0},
         {0, 1, 0, 0, 104, 0, 14, 0, 33, 0, 60, 1, 0, 0, 0, 0, 0, 0},
         {73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
         };
    
    int maxLinkCost=0;
    for(int i=0; i<nodes; i++) {
        for(int j=0; j<nodes; j++) {
            if(linkCosts[i][j]>maxLinkCost) maxLinkCost=linkCosts[i][j];
        }
    }
    System.out.println("Max link cost: "+maxLinkCost);
    
    assert initialNode>=0 && initialNode<nodes;
    assert linkCosts.length==nodes;
    assert linkCosts[0].length==nodes;
    
    Model model = new Model("MEB");
    
    IntVar[] parents = model.intVarArray("parents", nodes, 0, nodes-1);   // indexed by child node
    IntVar[] depths = model.intVarArray("depths", nodes, 0, nodes-1);    // indexed by node
    IntVar[] cost = model.intVarArray("cost", nodes, 1, maxLinkCost);
    IntVar optVar = model.intVar("optVar", 0, maxLinkCost*nodes);
    
    model.arithm(parents[initialNode], "=", initialNode).post();
    model.arithm(cost[initialNode], "=", 1).post();
    
    for(int child=0; child<nodes; child++) {
        if(child!=initialNode) {
            model.arithm(parents[child], "!=", child).post();
            
            // Assuming linkCosts is symmetric, i.e. can swap parent/child indexes
            // Index into linkCosts using the parent and store result in 'cost'
            model.element(cost[child], linkCosts[child], parents[child], 0).post();
            //  Constraint !=0 is implicit in domain of 'cost'.
            
            IntVar depthpar = model.intVar("depthpar"+child, 1, nodes);
            model.element(depthpar, depths, parents[child], 0).post();
            
            model.arithm(depths[child], ">", depthpar).post();
        }
    }
    
    IntVar[] costmaxs=model.intVarArray("costmaxs", nodes, 0, maxLinkCost);
    for(int parent=0; parent<nodes; parent++) {
        // Take the max of transmitting to its children
        
        IntVar[] costmaxpart=model.intVarArray("costmaxpart["+parent+"]", nodes, 0, maxLinkCost);
        
        for(int poschild=0; poschild<nodes; poschild++) {
            // parents[poschild]!=parent, then costmaxpart will be 0.
            // Otherwise, costmaxpart will be the linkCost of parent to child. 
            IntVar reifvar=model.arithm(parents[poschild], "=", parent).reify();
            model.arithm(reifvar, "*", model.intVar(linkCosts[parent][poschild]), "=", costmaxpart[poschild]).post();
        }
        model.max(costmaxs[parent], costmaxpart).post();
    }
    
    int[] coeffs = new int[nodes];
    for(int i=0; i<nodes; i++) coeffs[i]=1;
    model.scalar(costmaxs, coeffs, "=", optVar).post();
    
    model.setObjective(Model.MINIMIZE, optVar);
    
    ////////////////////////////////////////////////////////////////////////////
    
    //  Collect decision variables into one array. 
    IntVar[] decvars=new IntVar[4*nodes];
    for(int i=0; i<nodes; i++) {
        decvars[i]=parents[i];
        decvars[i+nodes]=depths[i];
        decvars[i+(2*nodes)]=cost[i];
        decvars[i+(3*nodes)]=costmaxs[i];
    }
    //decvars[4*nodes]=optVar;
    
    System.out.println("Starting search.");
    
    // Set up basic search for first sol.
    Move basicsearch=new MoveBinaryDFS(new DomOverWDeg(decvars, 992634, new IntDomainMin()));
    model.getSolver().setMove(basicsearch);
    
    boolean foundFirstSol=model.getSolver().solve();
    if(foundFirstSol) {
        System.out.println("First solution:");
        System.out.println(optVar.getValue());
    }
    else {
        System.out.println("No first solution found.");
    }
    
    //   Type of LNS neighbourhood -- propagation-guided LNS.
    //INeighbor in=INeighborFactory.propagationGuided(decvars);
    INeighbor in=INeighborFactory.explanationBased(decvars);
    
    in.init(); // Should this be necessary?
    
    //   Type of search within LNS neighbourhoods
    Move innersearch=new MoveBinaryDFS(new DomOverWDeg(decvars, 843746, new IntDomainMin()));
    
    MoveLNS lns=new MoveLNS(innersearch, in, new BacktrackCounter(model, 100000));
    
    model.getSolver().setMove(lns);
    
    Solution incumbent=null;
    for(int iter=0; iter<10000; iter++) {
        //  Run search in one neighbourhood...?
        boolean interimsol=model.getSolver().solve();
        
        if(interimsol) {
            System.out.println(optVar.getValue());
            for(int i=0; i<parents.length; i++) {
                System.out.println("parents["+i+"]="+parents[i].getValue());
            }
            for(int i=0; i<depths.length; i++) {
                System.out.println("depths["+i+"]="+depths[i].getValue());
            }
        }
        else {
            System.out.println("false");
        }
    }
}
}

```

**Comment by cprudhom** [comment]
Hi Peter, 

First, thank you for the bug reporting. 
I found where the bug comes from, I just need to find the right patch though.
Once done, I will push the correction, certainly today.
And the release should be done before December.

I plan to integrate in the near future (by the end of the year) a new version of the explanation system that will impact explanation-based LNS. 

Best,

**Comment by pwn1** [comment]
Hi Charles,

Many thanks for this, I have it working now on several larger examples of Minimum Energy Broadcast. 

Best wishes,
Peter
