### ISSUE TITLE
[BUG] Memory management problem?

### ISSUE THREAD

**Issue by JiiTee** [chocoteam/choco-solver#578]
## Expected behavior
Repeated posting and unposting of constraints does not consume extra memory or start slowing down Choco.

## Actual behavior
Repeated posting and unposting constraints starts slowing down Choco and may cause out of Heap Space. The example code with default memory settings within Eclipse on Windows crashes at about 9500. Slowing down around 8000.

```
Solution 9523 found :1658 ms. a = 9522, b = 2, 
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.stream.ForEachOps.makeRef(ForEachOps.java:73)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.chocosolver.solver.Solver.initialize(Solver.java:400)
	at org.chocosolver.solver.Solver.solve(Solver.java:260)
	at ChocoStressTest.IntMod.main(IntMod.java:39)

```

## Steps to Reproduce (for bugs)
```
package ChocoStressTest;

import java.util.LinkedList;

import org.chocosolver.solver.Model;
import org.chocosolver.solver.constraints.Constraint;
import org.chocosolver.solver.variables.IntVar;
import org.chocosolver.solver.variables.Variable;

public class IntMod {

    public static void main(String[] args) {

        LinkedList<Variable> printVars = new LinkedList<Variable>();
        Model model = new Model("model");

        IntVar a= model.intVar("a", 0, 10000, false);
        IntVar b= model.intVar("b", 0, 100, false);
        
        printVars.add(a);
        printVars.add(b);
        
        System.out.println(model);

        IntVar ten = model.intVar(10);
        Constraint modC = model.mod(a, ten, b);
        modC.post();
        
        int i=0;
        
        long timeMs = System.currentTimeMillis();
        long newTimeMs = System.currentTimeMillis();
        for (int aNow =a.getLB(); aNow<a.getUB(); aNow++) {
            Constraint ra = model.arithm(a, "=", aNow);
            model.post(ra);
            for (int bNow =b.getLB(); bNow < b.getUB(); bNow++) {
                Constraint rb = model.arithm(b, "=", bNow);
                model.post(rb);
                while (model.getSolver().solve()) {
                    i++;
                    newTimeMs = System.currentTimeMillis();
                    System.out.print("Solution " + i + " found :" + (newTimeMs-timeMs) + " ms. ");
                    timeMs = newTimeMs;
                    for(Variable v: printVars) System.out.print(v + ", ");
                    System.out.println("");
                }
                model.unpost(rb);
                model.getSolver().reset();
            }
            model.unpost(ra);
            model.getSolver().reset();
        }
    }
}


```

## Context
JUnit tests of a larger system where Choco is being applied. 

## Environment

* Choco-solver version: 4.0.6
* Java version: 8.xx, Windows
* Link to your project:

**Comment by cprudhom** [comment]
That's because, by default, we check that all declared constraints are posted or reified.
That should either be disabled by default, or checked programmatically.
In the meanwhile, you can disable it like that:

```java
Model model = new Model("model");
        model.set(new Settings() {
            @Override
            public boolean checkDeclaredConstraints() {
                return false;
            }
        });
```

I keep the issue open until I found the right patch to this issue.

**Comment by JiiTee** [comment]
Thank you for the work-around! I'll try it out.

**Comment by cprudhom** [comment]
Part of commit 70fc4ce04b8abb21db3e7847eb331201ed3c35a3 set the default value to `false`.
