### ISSUE TITLE
Installing Ibex 2.8.7 with Choco 4.10.2 under Ubuntu 16.04 32-bit virtual machine

### ISSUE THREAD

**Issue by begumgenc** [chocoteam/choco-solver#672]
Dear developers, 

I have been trying to install Ibex solver to be used with Choco for a few days now. I was unable to install it on my 64 bit machine, so I created a virtual machine with 32-bit Linux installed on it, and followed all the instructions. The _gaol_ library produced some errors for some reason, so I made use of the library _direct_.  The installation seemed successful, I did not get any errors. Please see the output of the process in file "output_install".
[output_install.txt](https://github.com/chocoteam/choco-solver/files/4231260/output_install.txt)

However, when I try to run a sample code, I get the error:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: no ibex-java in java.library.path
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
> 	at java.lang.System.loadLibrary(System.java:1124)
> 	at org.chocosolver.solver.constraints.real.Ibex.<clinit>(Ibex.java:62)
> 	at org.chocosolver.solver.constraints.real.IbexHandler.createInstance(IbexHandler.java:298)
> 	at org.chocosolver.solver.constraints.real.IbexHandler.getIbexInstance(IbexHandler.java:218)
> 	at org.chocosolver.solver.constraints.real.IbexHandler.contract(IbexHandler.java:122)
> 	at org.chocosolver.solver.constraints.real.RealPropagator.propagate(RealPropagator.java:85)
> 	at org.chocosolver.solver.propagation.PropagationEngine.execute(PropagationEngine.java:216)
> 	at org.chocosolver.solver.propagation.PropagationEngine.activatePropagators(PropagationEngine.java:200)
> 	at org.chocosolver.solver.propagation.PropagationEngine.propagate(PropagationEngine.java:164)
> 	at org.chocosolver.solver.Solver.propagate(Solver.java:627)

I set the library path as ~/workspace/Ibex/ibex-lib-ibex-2.8.7/lib and I have the following files produced:

> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/libibex.so
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/libibex-java.so
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libgaol.a
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libgaol.la
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libgdtoa.a
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libgdtoa.la
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libprim.a
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libprim.la
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libsoplex.a
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libsoplex.linux.x86.gnu.opt.a
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libsoplex-4.0.2.linux.x86.gnu.opt.a
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libultim.a
> /home/begum/workspace/Ibex/ibex-lib-ibex-2.8.7/lib/ibex/3rd/libultim.la

Would you be able to help me with fixing this problem? 

Thanks,

**Comment by schmittjoaopedro** [comment]
Hello,

Try to execute the steps in this [link](https://github.com/ibex-team/ibex-java/issues/3)
