### ISSUE TITLE
Bug using equation API

### ISSUE THREAD

**Issue by Lfschmitt** [chocoteam/choco-solver#698]
I'm trying to solve a simple maximization problem, where both variables are real numbers. The source follows below:

```java
Model model = new Model();
// Variables
RealVar t = model.realVar("t", 0.0, 10.0, 0.1);
RealVar h = model.realVar("h", 0.0, 10.0, 0.1);
// h = -3/4*t^2 + 6*t - 9
h.eq(t.mul(t).mul(-0.75).add(t.mul(6)).sub(9)).equation().post();
//t.eq(4).post(); // If uncommented it works
model.setObjective(Model.MAXIMIZE, h);
while (model.getSolver().solve()) ;
System.out.println(h);
System.out.println(t);
```
When I uncomment the line `t.eq(4).post();` the program works perfectly. However, If I try to execute the program to maximize h, without restricting t the program throws the following exception:

```java
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Exception in thread "main" org.chocosolver.solver.exception.SolverException: The current solution does not satisfy the checker.Either (a) the search strategy is not complete or (b) the model is not constrained enough or (c) a constraint's checker ("isSatisfied()") is not correct or (d) some constraints' filtering algorithm ("propagate(...)") is not correct.

##################################################

##################################################
FAILURE >> Equation ([SUB(h = [0,2170351211470497 .. 0,2170351211470497],SUB(ADD(MUL(MUL(t = [2,0361724387426547 .. 2,0443507165807730],t = [2,0361724387426547 .. 2,0443507165807730]),cste -- -0.75),MUL(t = [2,0361724387426547 .. 2,0443507165807730],cste -- 6.0)),cste -- 9.0)) = [0.0,0.0]])

==================================================
Path[21]: ROOT, t <= 4.0234375, t <= 2.989898204803466, t <= 2.484157863851634, t <= 2.236712425358128, t <= 2.1156801592434045, t <= 2.0565038432193696, !h <= 0.3470351211470498, !h <= 0.3370351211470498, !h <= 0.3270351211470498, !h <= 0.3170351211470498, !h <= 0.3070351211470498, !h <= 0.2970351211470498, !h <= 0.28703512114704977, !h <= 0.27703512114704976, !h <= 0.26703512114704975, !h <= 0.25703512114704974, !h <= 0.24703512114704973, !h <= 0.23703512114704972, !h <= 0.2270351211470497, h <= 0.2170351211470497
MAXIMIZE h = -0,0001
Model[Model-0], 0 Solutions, MAXIMIZE h = -0,0001, Resolution time 0,053s, Time to best solution 0,000s, 21 Nodes (394,8 n/s), 13 Backtracks, 0 Backjumps, 13 Fails, 0 Restarts##################################################

	at org.chocosolver.solver.Solver.validate(Solver.java:493)
	at org.chocosolver.solver.Solver.searchLoop(Solver.java:305)
	at org.chocosolver.solver.Solver.solve(Solver.java:260)
	at org.example.App.exercise54(App.java:30)
	at org.example.App.main(App.java:17)
```

Am I doing something wrong?

**Comment by cprudhom** [comment]
Thank you for the bug report.
I'll fix it in the next commit.
