### ISSUE TITLE
failures when compiling

### ISSUE THREAD

**Issue by glelouet** [chocoteam/choco-solver#735]
executing with a fresh repository, as explained [here](https://github.com/chocoteam/choco-solver/issues/699#issuecomment-688855606), without -DskipTests

```

[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for choco 4.10.5-SNAPSHOT:
[INFO] 
[INFO] choco .............................................. SUCCESS [  4.505 s]
[INFO] choco-sat .......................................... SUCCESS [ 11.544 s]
[INFO] choco-solver ....................................... FAILURE [40:28 min]
[INFO] choco-parsers ...................................... SKIPPED
[INFO] examples ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  40:45 min
[INFO] Finished at: 2020-09-17T16:55:36+02:00
[INFO] ------------------------------------------------------------------------


```

Here are the last lines, those that contain the failure : 

```
	org.chocosolver.solver.constraints.real.RealTest.test1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.test2 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.test4 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testDetec .... SUCCESS (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testElt1 .... SUCCESS (2ms)
	org.chocosolver.solver.constraints.real.RealTest.testElt2 .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testFN1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testFN1a .... SUCCESS (2ms)
	org.chocosolver.solver.constraints.real.RealTest.testFN2 .... FAILURE (4ms)
	org.chocosolver.solver.constraints.real.RealTest.testFreemajb1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testFreemajb2 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testFreemajb2b .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testFreemajb3 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM1 .... FAILURE (2ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM1 .... FAILURE (6ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM1a .... SUCCESS (10ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM1b .... SUCCESS (8ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM2 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM21 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM2a .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJJ1 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testJJ2 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testJJ3 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testJJ34 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJJ35 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJiTee1 ..At least one constraint is free, i.e., neither posted or reified. ).
REALCONSTRAINT ([RealPropagator(dim_A) ->("{0} > 315")]) is free
.. FAILURE (22626ms)
	org.chocosolver.solver.constraints.real.RealTest.testJiTee1a .... SUCCESS (21537ms)
	org.chocosolver.solver.constraints.real.RealTest.testJiiTee1 .... FAILURE (2ms)
	org.chocosolver.solver.constraints.real.RealTest.testJiiTee1a .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJoao2 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testJoao3 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJuha1 .... FAILURE (3ms)
	org.chocosolver.solver.constraints.real.RealTest.testJuha2 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJuha2a .... SUCCESS (3ms)
	org.chocosolver.solver.constraints.real.RealTest.testJuha2b .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove2 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove3 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove4 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove4a .... SUCCESS (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove5 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove5a .... SUCCESS (2ms)
	org.chocosolver.solver.constraints.real.RealTest.testPG1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testPeter .... FAILURE (5ms)
	org.chocosolver.solver.constraints.real.RealTest.testPetera .... SUCCESS (152ms)
	org.chocosolver.solver.constraints.real.RealTest.testPostUnpost .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testRoberto1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testRoberto1a .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testRoberto3 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testRoberto4 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testSchmitt .... SUCCESS (4ms)
	org.chocosolver.solver.constraints.real.RealTest.testSchmitt2 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJuha3 ..	org.chocosolver.solver.constraints.real.RealTest.testJuha3 ..	org.chocosolver.solver.constraints.real.RealTest.testJuha3 ..At least one constraint is free, i.e., neither posted or reified. ).
NOTMEMBER ([v_0 ∈ [1,1]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_1 ∈ [2,2]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_1 ∈ [3,3]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
NOTMEMBER ([v_1 ∈ [4,4]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v	org.chocosolver.solver.constraints.real.RealTest.test1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.test2 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.test4 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testDetec .... SUCCESS (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testElt1 .... SUCCESS (2ms)
	org.chocosolver.solver.constraints.real.RealTest.testElt2 .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testFN1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testFN1a .... SUCCESS (2ms)
	org.chocosolver.solver.constraints.real.RealTest.testFN2 .... FAILURE (4ms)
	org.chocosolver.solver.constraints.real.RealTest.testFreemajb1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testFreemajb2 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testFreemajb2b .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testFreemajb3 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM1 .... FAILURE (2ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM1 .... FAILURE (6ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM1a .... SUCCESS (10ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM1b .... SUCCESS (8ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM2 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM21 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testHM2a .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJJ1 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testJJ2 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testJJ3 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testJJ34 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJJ35 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJiTee1 ..At least one constraint is free, i.e., neither posted or reified. ).
REALCONSTRAINT ([RealPropagator(dim_A) ->("{0} > 315")]) is free
.. FAILURE (22626ms)
	org.chocosolver.solver.constraints.real.RealTest.testJiTee1a .... SUCCESS (21537ms)
	org.chocosolver.solver.constraints.real.RealTest.testJiiTee1 .... FAILURE (2ms)
	org.chocosolver.solver.constraints.real.RealTest.testJiiTee1a .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJoao2 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testJoao3 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJuha1 .... FAILURE (3ms)
	org.chocosolver.solver.constraints.real.RealTest.testJuha2 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJuha2a .... SUCCESS (3ms)
	org.chocosolver.solver.constraints.real.RealTest.testJuha2b .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove2 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove3 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove4 .... FAILURE (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove4a .... SUCCESS (0ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove5 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testMove5a .... SUCCESS (2ms)
	org.chocosolver.solver.constraints.real.RealTest.testPG1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testPeter .... FAILURE (5ms)
	org.chocosolver.solver.constraints.real.RealTest.testPetera .... SUCCESS (152ms)
	org.chocosolver.solver.constraints.real.RealTest.testPostUnpost .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testRoberto1 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testRoberto1a .... SUCCESS (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testRoberto3 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testRoberto4 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testSchmitt .... SUCCESS (4ms)
	org.chocosolver.solver.constraints.real.RealTest.testSchmitt2 .... FAILURE (1ms)
	org.chocosolver.solver.constraints.real.RealTest.testJuha3 ..	org.chocosolver.solver.constraints.real.RealTest.testJuha3 ..	org.chocosolver.solver.constraints.real.RealTest.testJuha3 ..At least one constraint is free, i.e., neither posted or reified. ).
NOTMEMBER ([v_0 ∈ [1,1]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_1 ∈ [2,2]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_1 ∈ [3,3]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
NOTMEMBER ([v_1 ∈ [4,4]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_0 ∈ [5,5]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_4 ∈ [3,3]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_0 ∈ [6,7]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_7 ∈ [4,5]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
NOTMEMBER ([v_8 ∈ [2,4]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_6 ∈ [4,6]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_1 ∈ [2,2]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 4]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 9]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 8]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 13]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 3]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 10]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 7]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 4]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 12]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 6]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 13]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 7]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
NOTMEMBER ([y ∈ [1,1]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 4]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 9]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 8]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 13]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 3]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 10]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 7]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 4]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 12]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 6]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 13]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 7]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_6 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_45 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_18 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_63 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_411 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_153 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_546 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_6 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_501 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_6 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_3 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_6 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_3 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_3 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_3 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_15 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_3 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_18 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_21 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([A = 9]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([Y >= X + 9]) is free

```_0 ∈ [5,5]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_4 ∈ [3,3]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_0 ∈ [6,7]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_7 ∈ [4,5]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
NOTMEMBER ([v_8 ∈ [2,4]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_6 ∈ [4,6]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
MEMBER ([v_1 ∈ [2,2]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 4]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 9]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 8]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 13]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 3]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 10]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 7]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 4]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 12]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 6]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 13]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 7]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
NOTMEMBER ([y ∈ [1,1]]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 4]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 9]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 8]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 13]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 3]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 10]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 7]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 4]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 12]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 6]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([x = 13]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 7]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([y = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([prop(x.EQ.y)]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_6 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_45 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_18 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_63 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_411 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_153 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_546 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_6 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_501 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_6 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_3 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_6 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_3 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_3 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_3 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_15 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_3 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_18 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([IV_21 = 2]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([A = 9]) is free
At least one constraint is free, i.e., neither posted or reified. ).
ARITHM ([Y >= X + 9]) is free

**Comment by glelouet** [comment]
here is the content of solver/target/surefire-reports/X.dump

```
# Created at 2020-09-17T16:55:36.180
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.chocosolver.solver@4.10.5-SNAPSHOT/org.chocosolver.solver.constraints.extension.nary.PropTableStr2.toString(PropTableStr2.java:111)
	at org.chocosolver.solver@4.10.5-SNAPSHOT/org.chocosolver.solver.exception.ContradictionException.toString(ContradictionException.java:65)
	at java.base/java.lang.String.valueOf(String.java:3352)
	at java.base/java.io.PrintWriter.println(PrintWriter.java:836)
	at java.base/java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:778)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:669)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:735)
	at org.testng.internal.Utils.buildStackTrace(Utils.java:320)
	at org.testng.internal.Utils.longStackTrace(Utils.java:303)
	at org.testng.reporters.TestHTMLReporter.generateTable(TestHTMLReporter.java:169)
	at org.testng.reporters.TestHTMLReporter.generateLog(TestHTMLReporter.java:359)
	at org.testng.reporters.TestHTMLReporter.onFinish(TestHTMLReporter.java:38)
	at org.testng.TestRunner.fireEvent(TestRunner.java:893)
	at org.testng.TestRunner.afterRun(TestRunner.java:857)
	at org.testng.TestRunner.run(TestRunner.java:588)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)



```

**Comment by cprudhom** [comment]
We used to run the test phase with `-Dgroups="1s"` or `-Dgroups="10s"`.
 
Most of the errors (all?) are due to the fact that `Ibex` is not installed on your computer (`-Dgroups="ibex"`).
You can have a look at [before_install.sh](https://github.com/chocoteam/choco-solver/blob/master/scripts/before_install.sh) for installation details.

**Comment by glelouet** [comment]
Thank you Charles.

I was about to propose to throw exception if there are free constraints, with an option to allow it in the model, but it seems it's an expected behavior.

BTW I have an issue to open the project with eclipse : since the git project is "choco-solver", but also the solver in itself is in another "choco-solver" project, eclipse wants to add two projects named "choco-solver"

**Comment by cprudhom** [comment]
Could you create a new issue ?

**Comment by glelouet** [comment]
it's handled by checking out the project in another name, like "choco". or rename it before adding it to eclipse.
