### ISSUE TITLE
[chocograph] Bug on circuit propagator ? "It is forbidden to remove an element from a constant set (Set_CstInterval)"

### ISSUE THREAD

**Issue by glelouet** [chocoteam/choco-solver#764]
minimal problem : 3 nodes 0, 1, 2 ; one arc from a node to the next and reciprocally. The node 1 is mandatory.Then I add the circuit constraint. 

```java
@Test
	public void test3steps() {
		GraphModel model = new GraphModel();
		DirectedGraph lb = new DirectedGraph(3, SetType.BITSET, false);
		lb.addNode(1);
		DirectedGraph ub = new DirectedGraph(3, SetType.BITSET, true);
		ub.addArc(0, 1);
		ub.addArc(1, 0);
		ub.addArc(1, 2);
		ub.addArc(2, 1);
		DirectedGraphVar graphVar = model.digraphVar("route", lb, ub);
		model.circuit(graphVar).post();
	
		model.getSolver().findSolution();
	}	
```

The initial problem is a bit more complex since I add a gain variable to maximize, that is the sum of the nodes of the graph index : 
``` java
		IntVar sumPoints = model.intVar("points", 0, Integer.MAX_VALUE / 2);
		model.sumElements(model.nodeSet(graphVar), new int[] { 0, 1, 2 }, sumPoints).post();
		model.getSolver().findOptimalSolution(sumPoints, true);

```

In both cases I get the same exception

> FAILED: test3steps
> java.lang.UnsupportedOperationException: It is forbidden to remove an element from a constant set (Set_CstInterval)
> 	at org.chocosolver.util.objects.setDataStructures.constant.Set_CstInterval.remove(Set_CstInterval.java:65)
> 	at org.chocosolver.util.objects.graphs.DirectedGraph.removeNode(DirectedGraph.java:129)
> 	at org.chocosolver.graphsolver.variables.GraphVar.removeNode(GraphVar.java:128)
> 	at org.chocosolver.graphsolver.cstrs.degree.PropNodeDegree_AtLeast_Incr.checkAtLeast(PropNodeDegree_AtLeast_Incr.java:165)
> 	at org.chocosolver.graphsolver.cstrs.degree.PropNodeDegree_AtLeast_Incr.lambda$new$0(PropNodeDegree_AtLeast_Incr.java:74)
> 	at org.chocosolver.graphsolver.variables.delta.GraphDeltaMonitor.forEachArc(GraphDeltaMonitor.java:123)
> 	at org.chocosolver.graphsolver.cstrs.degree.PropNodeDegree_AtLeast_Incr.propagate(PropNodeDegree_AtLeast_Incr.java:129)
> 	at org.chocosolver.solver.propagation.hardcoded.SevenQueuesPropagatorEngine.propagate(SevenQueuesPropagatorEngine.java:201)
> 	at org.chocosolver.solver.search.loop.propagate.PropagateBasic.execute(PropagateBasic.java:27)
> 	at org.chocosolver.solver.Solver.propagate(Solver.java:411)
> 	at org.chocosolver.solver.Solver.searchLoop(Solver.java:294)
> 	at org.chocosolver.solver.Solver.solve(Solver.java:264)
> 	at org.chocosolver.solver.search.IResolutionHelper.findSolution(IResolutionHelper.java:91)

Adding an arc from 0 to 2 solves the issue; but it's a different problem.

``` java
@Test
	public void test3steps() {
		GraphModel model = new GraphModel();
		DirectedGraph lb = new DirectedGraph(3, SetType.BITSET, false);
		lb.addNode(1);
		DirectedGraph ub = new DirectedGraph(3, SetType.BITSET, true);
		ub.addArc(0, 1);
		ub.addArc(1, 0);
		ub.addArc(1, 2);
		ub.addArc(2, 1);
		ub.addArc(0, 2);
		DirectedGraphVar graphVar = model.digraphVar("route", lb, ub);
		model.circuit(graphVar).post();

		// model.getSolver().findSolution();

		IntVar sumPoints = model.intVar("points", 0, Integer.MAX_VALUE / 2);
		model.sumElements(model.nodeSet(graphVar), new int[] { 0, 1, 2 }, sumPoints).post();
		model.getSolver().findOptimalSolution(sumPoints, true);
	}
```

**Comment by glelouet** [comment]
Also I think chocograph should be merged into choco (unless it should not), and GraphVar should contain the variables for SetVar nodes() and co.

**Comment by cprudhom** [comment]
> Also I think chocograph should be merged into choco (unless it should not), and GraphVar should contain the variables for SetVar nodes() and co.

That's in the pipe:
https://github.com/chocoteam/choco-solver/projects/5/
